name: Test E2E

on:
  push:
  pull_request:
    branches:
    - main

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
    
    - run: npm ci

    - run: npm run download

    - run: |
        FILE=deleted_domains/`date +%Y`/`date +%m`/`date +%Y-%m-%d`.txt
        test -f "$FILE"       
